=== raybrm/IPL/2BIN/SD2/XML/1.BasesXML/fichePerso.dtd
<!ELEMENT fichier_personnel (personne)*>
<!ELEMENT personne (identite,bio,socio)>
<!ELEMENT identite ((nom,prenom)|(prenom,nom))>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT bio (yeux,cheveux,age,poids,groupe_sanguin)>
<!ELEMENT yeux EMPTY>
<!ATTLIST yeux couleur CDATA #REQUIRED>
<!ELEMENT cheveux EMPTY>
<!ATTLIST cheveux couleur CDATA #REQUIRED remarque CDATA #IMPLIED>
<!ELEMENT age (#PCDATA)>
<!ATTLIST age unite CDATA #FIXED "ans">
<!ELEMENT poids EMPTY>
<!ATTLIST poids kg CDATA #REQUIRED>
<!ELEMENT groupe_sanguin EMPTY>
<!ATTLIST groupe_sanguin type (A|B|0|AB) #REQUIRED>
<!ELEMENT socio (langue,etat_civil,passeport)>
<!ELEMENT langue EMPTY>
<!ATTLIST langue lang (de|en|fr|es|pt|it)  "fr" >
<!ELEMENT etat_civil EMPTY>
<!ATTLIST etat_civil type (celibataire|marie|veuf) #REQUIRED>
<!ELEMENT passeport EMPTY>
<!ATTLIST passeport nr ID #REQUIRED>

=== raybrm/IPL/2BIN/SD2/XML/1.BasesXML/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fichier_personnel SYSTEM "fichePerso.dtd" >
<fichier_personnel>
  <personne>
    <identite>
    	<nom> Cja</nom>
    	<prenom></prenom>
    </identite>
    <bio>
      <yeux couleur=""/>
      <cheveux couleur="" remarque=""/>
      <age unite="ans">age</age>
      <poids kg=""/>
      <groupe_sanguin type="A"/>
    </bio>
    <socio>
      <langue lang="fr"/>
      <etat_civil type="celibataire"/>
      <passeport nr="idvalue0"/>
    </socio>
  </personne>
</fichier_personnel>
